onlyBuiltDependencies:
  - @parcel/watcher
  - @sbc-connect/nuxt-auth
  - @sbc-connect/nuxt-base
  - @sbc-connect/nuxt-business-base
  - @sbc-connect/nuxt-forms
  - @sbc-connect/nuxt-pay
  - esbuild
  - unrs-resolver
  - vue-demi
