apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: preload-job-template
  labels:
    app: bor-solr
    name: bor-solr-preload-${ENV}
    role: job
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: bor-solr-preload
      namespace: 1dfe78-${ENV}
      labels:
        app: bor-solr
        name: bor-solr-preload-${ENV}
        role: job
    spec:
      template:
        metadata:
          name: bor-solr-preload-${ENV}
          labels:
            app: bor-solr
            name: bor-solr-preload-${ENV}
            role: job
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - cd /opt/app-root; ./run.sh
              env:
                - name: ORACLE_USER
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: ORACLE_USER
                - name: ORACLE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: ORACLE_PASSWORD
                - name: ORACLE_DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: ORACLE_DB_NAME
                - name: ORACLE_HOST
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: ORACLE_HOST
                - name: ORACLE_PORT
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: ORACLE_PORT
                - name: DATABASE_HOST_LEAR
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_HOST_LEAR
                - name: DATABASE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_NAME
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_PASSWORD
                - name: DATABASE_PORT
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_PORT
                - name: DATABASE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_USERNAME
                - name: POD_NAMESPACE
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: POD_NAMESPACE
                - name: SOLR_SVC_FOLLOWER_CORE
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: SOLR_SVC_FOLLOWER_CORE
                - name: SOLR_SVC_FOLLOWER_URL
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: SOLR_SVC_FOLLOWER_URL
                - name: SOLR_SVC_LEADER_CORE
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: SOLR_SVC_LEADER_CORE
                - name: SOLR_SVC_LEADER_URL
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: SOLR_SVC_LEADER_URL
                - name: SOLR_BATCH_UPDATE_SIZE
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: SOLR_BATCH_UPDATE_SIZE
                - name: BOR_API_INTERNAL_URL
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: BOR_API_INTERNAL_URL
                - name: BOR_API_VERSION
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: BOR_API_VERSION
                - name: KEYCLOAK_AUTH_TOKEN_URL
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: KEYCLOAK_AUTH_TOKEN_URL
                - name: NDS_SERVICE_ACCOUNT_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: NDS_SERVICE_ACCOUNT_CLIENT_ID
                - name: NDS_SERVICE_ACCOUNT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: NDS_SERVICE_ACCOUNT_SECRET
                - name: DATABASE_LOCATION
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_LOCATION
                - name: DATABASE_HOST_GCP
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_HOST_GCP
                - name: DATABASE_NAME_GCP
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_NAME_GCP
                - name: DATABASE_PASSWORD_GCP
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_PASSWORD_GCP
                - name: DATABASE_PORT_GCP
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_PORT_GCP
                - name: DATABASE_USERNAME_GCP
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: DATABASE_USERNAME_GCP
                - name: RESYNC_OFFSET
                  valueFrom:
                    secretKeyRef:
                      name: bor-solr-importer-${ENV}-secret
                      key: RESYNC_OFFSET
                - name: REINDEX_CORE
                  value: "True"
                - name: PRELOADER_JOB
                  value: "True"
                - name: FLASK_ENV
                  valueFrom:
                    secretKeyRef:
                      key: FLASK_ENV
                      name: bor-solr-importer-${ENV}-secret
              image: image-registry.openshift-image-registry.svc:5000/1dfe78-tools/bor-solr-importer:${ENV}
              imagePullPolicy: Always
              name: bor-solr-preload-${ENV}
              resources:
                limits:
                  cpu: '1'
                  memory: 20Gi
                requests:
                  cpu: 500m
                  memory: 10Gi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          activeDeadlineSeconds: 60000
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 300
parameters:
  - description: Environment job will be created in
    name: ENV
    required: true
