name: BOR Solr Importer CD

on:
  push:
    branches:
      - main
      - feature*
      - hotfix*
    paths:
      - "./bor-solr-importer/**"
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy To"
        required: true
        type: choice
        options:
          - "dev"
          - "test"
          - "sandbox"
          - "prod"
      redeploy:
        description: "Redeploy Application"
        required: true
        type: choice
        options:
          - "false"
          - "true"

jobs:
  bor-solr-importer-cd:
    permissions:
        contents: "write"
        id-token: "write"
    uses: bcgov/bcregistry-sre/.github/workflows/backend-cronjob-cd-ocp.yaml@main
    with:
      target: ${{ inputs.target }}
      app_name: "bor-solr-importer"
      working_directory: "./bor-solr-importer"
    secrets:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      OPENSHIFT_DOCKER_REGISTRY: ${{ secrets.OPENSHIFT_GOLD_DOCKER_REGISTRY }}
      OPENSHIFT_LOGIN_REGISTRY: ${{ secrets.OPENSHIFT_GOLD_LOGIN_REGISTRY }}
      OPENSHIFT_SA_NAME: ${{ secrets.OPENSHIFT_GOLD_SA_NAME }}
      OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_GOLD_SA_TOKEN }}
      OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT_GOLD_REPOSITORY }}
