name: BOR UI CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "bor-ui/**"


defaults:
  run:
    shell: bash
    working-directory: ./bor-ui

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    if: github.repository == 'bcgov-registries/beneficial-ownership'

    steps:
      - uses: actions/checkout@v3
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Linting
        run: pnpm lint

  test:
    needs: setup-job
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Run unit tests
        run: pnpm test:unit

  build-check:
    needs: setup-job
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Build check
        run: pnpm build

