name: BOR Solr Importer CI

on:
  pull_request:
    branches:
      - main
      - feature*
      - hotfix*
    paths:
      - "bor-solr-importer/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./bor-solr-importer

jobs:
  bor-importer-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "bor-solr-importer"
      working_directory: "./bor-solr-importer"
      codecov_flag: "bor-solr-importer"
