name: BOR UI SRE CI

on:
  pull_request:
    paths:
      - "bor-ui/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./bor-ui
jobs:
  bor-ui-ci:
    permissions:
      contents: "write"
      id-token: "write"
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      node_version: 20
      pnpm_version: 8
      app_name: "bor-ui"
      working_directory: "./bor-ui"
      codecov_flag: "borui"
