name: BOR API CI

on:
  pull_request:
    paths:
      - "bor-api/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./bor-api

jobs:
  bor-api-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "bor-api"
      working_directory: "./bor-api"
      codecov_flag: "borapi"